name: "Pretty Linter"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20.16.0"

jobs:
  pretty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run pretty:fix

      - name: Commit Prettier Fixes
        if: github.actor != 'github-actions[bot]'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-commit prettier fixes"
          branch: main
